### ISSUE TITLE
Incorrect Discharge Date Displayed for Army Service

### ISSUE THREAD

**Issue by gokoro** [SaidBySolo/take-me-home#2]
## Describe the bug
In the Army Service module of our application, the discharge date is not correctly displayed. When the user's service is ongoing, the discharge date should ideally display as 'INFINITY' to indicate an ongoing commitment. However, this is currently displaying an incorrect or arbitrary date.

## To Reproduce

Go to 'Profile'
Click on 'Army Service'
Under the 'Discharge Date' field, it's displaying a specific date instead of 'INFINITY' for active soldiers.

## Expected behavior
For service members who are currently serving, the discharge date should display as 'INFINITY'. This would provide a clear indication that the service member is still actively serving.

## Screenshots
<img width="902" alt="image" src="https://github.com/SaidBySolo/take-me-home/assets/46917452/287d1e32-76f2-4192-89c4-8b8a879e2f91">

## Environment

OS: Windows 10
Browser: Google Chrome
Version: 90.0.4430.212

## Additional context
This issue is critical as it affects the clarity of information about active duty service members. It is essential to display 'INFINITY' for active soldiers to avoid confusion.

## Potential Solution
A potential fix might involve rechecking the logic that's responsible for displaying the discharge date. If the soldier is currently serving, instead of fetching and displaying a date, the system should return and display 'INFINITY'.

**Comment by gokoro** [comment]
I hope this bug will be solved ASAP 😄

**Comment by SaidBySolo** [comment]
Maybe fixed in #1?

**Comment by gokoro** [comment]
> Maybe fixed in #1?

@SaidBySolo It's hard to say that entire bugs have fully been fixed, but yeah, seems enough.
I'm closing this issue with hoping that your discharging date will never come 😃 😃 😃
